source ~/.vim/plugins.vim

" General
set noautochdir         " Don't chdir to the location where the file is by default
set confirm             " Instead of failing a command because of unsaved changes, instead raise a dialogue asking if you wish to save changed files.
set mouse=a             " Enable use of the mouse for all modes
set nobackup            " Don't create backup files
set noswapfile          " Don't create swap files
syntax enable           " enable syntax processing

" Colors 
colorscheme jellybeans

" Spaces & Tabs 
set tabstop=4           " 4 space tab
set expandtab           " use spaces for tabs
set softtabstop=4       " 4 space tab
set shiftwidth=4        " when indenting with '>', use 4 spaces width
set modelines=1
set autoindent
filetype indent on      " load filetype-specific indent files
filetype plugin on
nnoremap <tab> %        " Tab in normal mode is used to jump between parenthesis
vnoremap <tab> %        " Tab in normal mode is used to jump between parenthesis

" UI Layout
set number              " show line numbers
set relativenumber      " show relative line numbers
set showcmd             " show command in bottom bar
set cursorline          " highlight current line
set lazyredraw          " redraw only when we need to (e.g. don't redraw while executing macros)
set showmatch           " higlight matching parenthesis
set wildmenu            " visual autocomplete for command menu
set wildmode=longest:full,full
set wildignore=*.o,*~,*.pyc   " Ignore compiled files

" Searching 
set ignorecase smartcase          " make searches case-insensitive, unless they contain upper-case letters
set incsearch           " search as characters are entered
set incsearch showmatch hlsearch  " show the `best match so far' as search strings are typed and highlight it
nnoremap <C-L> :noh<CR><C-L>            " Map <C-L> (redraw screen) to also turn off search highlighting until the next search

" Folding
set foldmethod=indent   " fold based on indent level
set foldnestmax=10      " max 10 depth
set foldenable          " don't fold files by default on open
nnoremap <space> za
set foldlevelstart=10   " start with fold level of 1

" Line Shortcuts
map Y y$                " Map Y to act like D and C, i.e. to yank until EOL, rather than act as yy, which is the default

" Window
set splitright          " Force vsplit to open new window on the right
set splitbelow          " Force vsplit to open new window below
map <C-H> <C-W>h        " Move between split windows more naturally
map <C-J> <C-W>j
map <C-K> <C-W>k
map <C-L> <C-W>l        " replaces the "Redraw screen" action. :redraw doesn't do the same thing.

" vim's status line
set statusline=   " clear the statusline for when vimrc is reloaded
set statusline+=%-3.3n\                      " buffer number
set statusline+=%f\                          " file name
set statusline+=%h%m%r%w                     " flags
set statusline+=[%{strlen(&ft)?&ft:'none'},  " filetype
set statusline+=%{strlen(&fenc)?&fenc:&enc}, " encoding
set statusline+=%{&fileformat}]              " file format
set statusline+=%=                           " right align
set statusline+=%#Error#                     " color highlight for Syntastic error
set statusline+=%{SyntasticStatuslineFlag()} " Syntastic error location
set statusline+=%*                           " reset highlight
set statusline+=%-8.(%)                      " offset
set statusline+=%{synIDattr(synID(line('.'),col('.'),1),'name')}\  " highlight
set statusline+=%b,0x%-8B\                   " current char
set statusline+=%-14.(%l,%c%V%)\ %<%P        " offset
set laststatus=2        " Always display statusline, even if there's only one window in vim
